package com.spider.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.spider.common.model.User;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}
	
	

	public void setContent(java.math.BigDecimal content) {
		set("content", content);
	}

	public java.math.BigDecimal getContent() {
		return get("content");
	}
	
	public void setDate(java.util.Date date){
		set("date", date);
	}
	
	public java.util.Date getDate(){
		return get("date");
	}
	
	public void setRead(java.lang.Integer read){
		set("read",read);
	}
	public java.lang.Integer getRead(){
		return get("read");
	}
	
	public void setUserId(Integer userId){
		set("userId",userId);
	}
	public Integer getUserId(){
		return get("userId");
	}
	
	public void setDesc(String desc){
		set("desc", desc);
	}
	public String getDesc(String desc){
		return get("desc");
	}
	public User getUser(){
		return User.user.findById(get("userId"));
	}
	public static final String read = "read";
	public static final String userId = "userId";
	public static final String date = "date";
	public static final String content="content";
	public static final String title="title";
	public static final String id="id";
			
}
